name: Hello World
on:
  push:
    branches:
      - main
jobs:
  hello:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello World" > hello.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-artifact
          path: hello.txt